# Generated by Django 4.1.7 on 2023-09-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phoneno',
        ),
    ]
